### ISSUE TITLE
conflict with "import json"

### ISSUE THREAD

**Issue by MichiKuhl** [iotaledger/iota.lib.py#204]
I wanted  to use the Pyota library along with the json library and always got an error (AttributeError: 'module' object has no attribute 'dumps' )
Renaming the the json.py file in  /usr/local/lib/python2.7/dist-packages/iota helped to solve that issue.

**Comment by todofixthis** [comment]
Hey @MichiKuhl thanks for reporting this issue!

Couple of thoughts:

1. Could you attach a stack trace, so that I can review the files and code that were involved in the error?

2. Out of curiosity, if you activate [absolute imports](https://www.python.org/dev/peps/pep-0328/) in your script, does the error go away?

    Put the following code at the top of the Python file in question:

    ```python
    from __future__ import absolute_import
    ```

    We might still rename the library for compatibility, but this will help to diagnose the issue.

**Comment by todofixthis** [comment]
Hey @MichiKuhl it's been awhile; I'm going to go ahead and close this issue.  If you still need help with this issue, just post back and I'll have a look 😺
